### GET request for all users
GET http://localhost:3001/api/users

### POST request for a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "user.name",
  "firstName": "first",
  "lastName": "last",
  "email": "first.last@gmail.com",
  "password": "example"
}

### DELETE request for user by id
DELETE http://localhost:3001/api/users/4935a82e-affd-4ceb-bbeb-bfb85fa87e17

### GET request for all active sessions
GET http://localhost:3001/api/login

### POST request to log in
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "user.name",
  "password": "example"
}