### GET request for all users
GET http://localhost:3001/api/users

### POST request for a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "user.name",
  "firstName": "first",
  "lastName": "last",
  "email": "first.last@gmail.com",
  "password": "example"
}

### DELETE request for user by id
DELETE http://localhost:3001/api/users/4935a82e-affd-4ceb-bbeb-bfb85fa87e17

### GET request for all active sessions
GET http://localhost:3001/api/login

### POST request to log in
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "user.name",
  "password": "example"
}

### DELETE request to log out
DELETE http://localhost:3001/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2OTE2N2Q5LTIxOTktNDQzNy05OThhLTc3ZTM0NTMyMjExYyIsInVzZXJuYW1lIjoidXNlci5uYW1lIiwiaWF0IjoxNzA1MDgyOTA5fQ.DVGM9o5OAugZfWgAdvZhFgdKzXyQnZm6dBh2ojlWSMI
Content-Type: application/json